// Exercise Policy Map
// Defines runtime behavior, validation, and teacher rules for every exercise type.

import type { ExercisePolicy } from './exercise-protocols.js'
import type { CanonicalExerciseType } from './supported-exercise-types.js'

// ── Shared teacher behavior templates ────────────────────────────────────────

const DETERMINISTIC_BEHAVIOR: ExercisePolicy['teacherBehavior'] = {
  introRule: 'State the task instruction clearly. Do not explain grammar before the student attempts.',
  answerFormatRule: 'Tell student whether to say the missing word only or the full sentence.',
  correctionRule: 'If wrong: give a mini hint first, then a stronger hint, then reveal on third fail.',
  hintRule: 'Hint must not give away the answer directly. Point to a rule or pattern.',
  progressionRule: 'Do not advance to the next item until current item is correct or ladder is exhausted.',
  offTopicRule: 'Redirect gently: "Let\'s focus on this sentence first."',
  forbiddenBehaviors: [
    'Do not say "Wrong" or "Incorrect".',
    'Do not move forward while current item is incomplete.',
    'Do not reveal the answer on the first hint.',
    'Do not ask for all items at once.',
  ],
}

const MATCHING_BEHAVIOR: ExercisePolicy['teacherBehavior'] = {
  introRule: 'Show all left items and all right options. Ask one left item at a time.',
  answerFormatRule: 'Student may answer with the letter (A, B, C…) or the full option text.',
  correctionRule: 'If wrong: remind student to look at the remaining options. Then reveal on second fail.',
  hintRule: 'Narrow down by eliminating one obviously wrong option.',
  progressionRule: 'Confirm each pair before asking the next. Never ask for all pairs at once.',
  offTopicRule: 'Redirect: "Which option matches number X?"',
  forbiddenBehaviors: [
    'Never run matching without visible options.',
    'Never ask for all pairs simultaneously.',
    'Do not say "Wrong" or "Incorrect".',
    'Never invent options not in the original list.',
  ],
}

const SOFT_SPEAKING_BEHAVIOR: ExercisePolicy['teacherBehavior'] = {
  introRule: 'Frame the task as an open question or speaking prompt. No hard right/wrong.',
  answerFormatRule: 'Student speaks freely. No specific format required.',
  correctionRule: 'Give short positive feedback, then note one grammar or vocabulary improvement.',
  hintRule: 'Offer a sentence starter or vocabulary word if the student is stuck.',
  progressionRule: 'Move on after one substantive response. Do not loop for perfection.',
  offTopicRule: 'If completely off-task, refocus once: "Try to talk about [topic]."',
  forbiddenBehaviors: [
    'Never say "The correct answer is…" for open speaking.',
    'Do not use binary correct/wrong for open discussion.',
    'Do not force the student to repeat until exact match.',
    'Do not skip feedback entirely — always give one useful comment.',
  ],
}

const GRAMMAR_EXPLANATION_BEHAVIOR: ExercisePolicy['teacherBehavior'] = {
  introRule: 'Explain the grammar point briefly — 2–3 sentences max.',
  answerFormatRule: 'Ask one quick comprehension check question after the explanation.',
  correctionRule: 'If check question is wrong: re-explain the key part, then ask again.',
  hintRule: 'Point to the rule just explained.',
  progressionRule: 'Move to a supported practice exercise after the check is passed.',
  offTopicRule: 'Redirect: "Let me explain this grammar point first."',
  forbiddenBehaviors: [
    'Do not turn grammar_focus into a long lecture.',
    'Do not skip the practice exercise entirely.',
    'Do not leave the student without a check question.',
  ],
}

const UNSUPPORTED_BEHAVIOR: ExercisePolicy['teacherBehavior'] = {
  introRule: 'Do not attempt this exercise type in the current runtime.',
  answerFormatRule: 'N/A',
  correctionRule: 'N/A',
  hintRule: 'N/A',
  progressionRule: 'Skip or explain limitation to student.',
  offTopicRule: 'N/A',
  forbiddenBehaviors: [
    'Do not pretend to hear textbook audio.',
    'Do not invent audio content.',
    'Do not run writing tasks as voice exercises.',
    'Do not run long reading as a single item.',
    'Do not invent image or cartoon content.',
  ],
}

const TEXT_READING_BEHAVIOR: ExercisePolicy['teacherBehavior'] = {
  introRule: 'Confirm that options/items are visible on screen. Tell the student exactly which item to work on. Do not reference content not shown in the frontend payload.',
  answerFormatRule: 'Student reads from their textbook or the visible options and gives a specific answer (a letter, a word, or a name).',
  correctionRule: 'If wrong: ask the student to look again at the relevant part of the text or the visible options. Give one structural hint before a second attempt.',
  hintRule: 'Point to the visible option or ask a narrowing question about the text. Never give the answer directly on the first hint.',
  progressionRule: 'Confirm each answer before moving to the next item. Never skip ahead.',
  offTopicRule: 'Redirect: "Let\'s focus on this item first."',
  forbiddenBehaviors: [
    'NEVER say "look at the box" unless options/wordBox are in the frontend payload.',
    'NEVER describe text content that is not shown in the payload.',
    'NEVER invent sentence options or gap answers.',
    'If required content is missing from payload: say "This reading exercise is not fully loaded on screen yet, so we cannot do this item safely." — do not improvise.',
    'Do not say "Wrong" or "Incorrect" — use guiding correction language.',
    'Do not skip items without confirming with student.',
  ],
}

// ── Policy map ────────────────────────────────────────────────────────────────

export const EXERCISE_POLICY_MAP: Record<CanonicalExerciseType, ExercisePolicy> = {

  // ── SUPPORTED: Structured grammar/vocabulary ─────────────────────────────

  fill_gap: {
    canonicalType: 'fill_gap',
    aliases: ['fill_in_the_blank', 'fill_in', 'gap_fill', 'fill_gaps'],
    detectionSignals: ['fill in the blanks', 'fill in', 'complete the sentences', 'complete with', 'use the words in the box', 'choose from the box'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'deterministic_normalized',
    progressionMode: 'locked_item',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: {
      ...DETERMINISTIC_BEHAVIOR,
      introRule: 'Show one sentence with one gap at a time. State whether student should say missing word only or full sentence.',
    },
  },

  choose_from_box: {
    canonicalType: 'choose_from_box',
    aliases: ['use_the_words', 'word_box'],
    detectionSignals: ['use the words in the box', 'choose from the box', 'words in the box', 'from the box'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'deterministic_normalized',
    progressionMode: 'locked_item',
    voiceFriendliness: 'high',
    requiresOptions: true,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: {
      ...DETERMINISTIC_BEHAVIOR,
      introRule: 'Show the word box and one sentence at a time. Remind student which words are available.',
    },
  },

  complete_correct_form: {
    canonicalType: 'complete_correct_form',
    aliases: ['correct_form', 'verb_form', 'put_in_correct_form'],
    detectionSignals: ['correct form', 'complete with the correct form', 'verbs in brackets', 'put the verb', 'use the correct form'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'deterministic_normalized',
    progressionMode: 'locked_item',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: DETERMINISTIC_BEHAVIOR,
  },

  form_transformation: {
    canonicalType: 'form_transformation',
    aliases: ['sentence_transformation', 'transformation'],
    detectionSignals: ['transform', 'change the sentence', 'rewrite using', 'complete the second sentence'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'deterministic_normalized',
    progressionMode: 'locked_item',
    voiceFriendliness: 'medium',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: DETERMINISTIC_BEHAVIOR,
  },

  rewrite_sentence: {
    canonicalType: 'rewrite_sentence',
    aliases: ['rewrite'],
    detectionSignals: ['rewrite', 'rewrite the sentence', 'rewrite so that', 'rewrite using'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'ai_semantic',
    progressionMode: 'locked_item',
    voiceFriendliness: 'medium',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: DETERMINISTIC_BEHAVIOR,
  },

  write_sentences_from_prompts: {
    canonicalType: 'write_sentences_from_prompts',
    aliases: [],
    detectionSignals: ['write sentences', 'make sentences', 'write a sentence about', 'write sentences using'],
    supportStatus: 'supported',
    runtimeMode: 'soft_speaking',
    validationMode: 'soft_ai_feedback',
    progressionMode: 'soft_completion',
    voiceFriendliness: 'medium',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: SOFT_SPEAKING_BEHAVIOR,
  },

  reconstruction: {
    canonicalType: 'reconstruction',
    aliases: ['word_order', 'put_in_order', 'sentence_building'],
    detectionSignals: ['put the words in order', 'put the words in the correct order', 'make sentences', 'rearrange'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'ai_semantic',
    progressionMode: 'locked_item',
    voiceFriendliness: 'medium',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: DETERMINISTIC_BEHAVIOR,
  },

  write_questions: {
    canonicalType: 'write_questions',
    aliases: [],
    detectionSignals: ['write questions', 'form questions', 'make questions', 'write the question'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'ai_semantic',
    progressionMode: 'locked_item',
    voiceFriendliness: 'medium',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: DETERMINISTIC_BEHAVIOR,
  },

  error_correction: {
    canonicalType: 'error_correction',
    aliases: ['find_the_mistake', 'correct_the_error', 'find_and_correct', 'spot_the_error'],
    detectionSignals: ['find the mistake', 'correct the error', 'find and correct', 'spot the mistake', 'correct the sentences'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'deterministic_normalized',
    progressionMode: 'locked_item',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: DETERMINISTIC_BEHAVIOR,
  },

  matching: {
    canonicalType: 'matching',
    aliases: ['match', 'match_words', 'link_words', 'pair_words'],
    detectionSignals: [
      'match', 'match questions', 'match words', 'with their opposites',
      '1–5 with a–e', '1-5 with a-e', 'questions with answers', 'words with definitions',
      'match the words', 'match each', 'match adjectives', 'link the words',
    ],
    supportStatus: 'supported',
    runtimeMode: 'matching_sequential',
    validationMode: 'matching_letter_or_text',
    progressionMode: 'one_match_at_a_time',
    voiceFriendliness: 'high',
    requiresOptions: true,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: MATCHING_BEHAVIOR,
  },

  vocabulary_matching: {
    canonicalType: 'vocabulary_matching',
    aliases: ['vocabulary', 'word_match'],
    detectionSignals: ['match the vocabulary', 'match the words with their meanings', 'match definitions', 'word meanings'],
    supportStatus: 'supported',
    runtimeMode: 'matching_sequential',
    validationMode: 'matching_letter_or_text',
    progressionMode: 'one_match_at_a_time',
    voiceFriendliness: 'high',
    requiresOptions: true,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: MATCHING_BEHAVIOR,
  },

  collocations: {
    canonicalType: 'collocations',
    aliases: [],
    detectionSignals: ['collocation', 'collocations', 'word partnerships', 'words that go together'],
    supportStatus: 'supported',
    runtimeMode: 'matching_sequential',
    validationMode: 'deterministic_normalized',
    progressionMode: 'one_match_at_a_time',
    voiceFriendliness: 'high',
    requiresOptions: true,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: MATCHING_BEHAVIOR,
  },

  find_opposites: {
    canonicalType: 'find_opposites',
    aliases: [],
    detectionSignals: ['find the opposite', 'find opposites', 'opposite meaning', 'antonyms', 'with their opposites'],
    supportStatus: 'supported',
    runtimeMode: 'matching_sequential',
    validationMode: 'deterministic_normalized',
    progressionMode: 'one_match_at_a_time',
    voiceFriendliness: 'high',
    requiresOptions: true,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: MATCHING_BEHAVIOR,
  },

  replace_substitute_words: {
    canonicalType: 'replace_substitute_words',
    aliases: [],
    detectionSignals: ['replace the words', 'substitute', 'replace with', 'find a word to replace'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'deterministic_normalized',
    progressionMode: 'locked_item',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: DETERMINISTIC_BEHAVIOR,
  },

  tick_cross: {
    canonicalType: 'tick_cross',
    aliases: [],
    detectionSignals: ['tick or cross', 'tick the correct', 'mark with a tick', 'correct or incorrect'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'deterministic_exact',
    progressionMode: 'locked_item',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: DETERMINISTIC_BEHAVIOR,
  },

  true_false: {
    canonicalType: 'true_false',
    aliases: [],
    detectionSignals: ['true or false', 'true/false', 'is it true', 'decide if'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'deterministic_exact',
    progressionMode: 'locked_item',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: DETERMINISTIC_BEHAVIOR,
  },

  multiple_choice: {
    canonicalType: 'multiple_choice',
    aliases: [],
    detectionSignals: ['choose the correct answer', 'circle the correct', 'choose a b c or d', 'choose the best answer'],
    supportStatus: 'supported',
    runtimeMode: 'deterministic_sequential',
    validationMode: 'matching_letter_or_text',
    progressionMode: 'locked_item',
    voiceFriendliness: 'high',
    requiresOptions: true,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: {
      ...MATCHING_BEHAVIOR,
      introRule: 'Read the question and all options. Ask student to choose one.',
    },
  },

  // ── SUPPORTED: Speaking / Discussion ────────────────────────────────────────

  speaking_prompt: {
    canonicalType: 'speaking_prompt',
    aliases: ['speaking', 'free_speaking', 'free_production'],
    detectionSignals: ['talk about', 'tell your partner', 'speak about', 'say what you think', 'describe'],
    supportStatus: 'supported',
    runtimeMode: 'soft_speaking',
    validationMode: 'soft_ai_feedback',
    progressionMode: 'soft_completion',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: SOFT_SPEAKING_BEHAVIOR,
  },

  discussion: {
    canonicalType: 'discussion',
    aliases: ['talk', 'pair_discussion'],
    detectionSignals: ['discuss', 'in pairs', 'ask and answer', 'talk about', 'with a partner'],
    supportStatus: 'supported',
    runtimeMode: 'soft_speaking',
    validationMode: 'soft_ai_feedback',
    progressionMode: 'soft_completion',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: SOFT_SPEAKING_BEHAVIOR,
  },

  roleplay: {
    canonicalType: 'roleplay',
    aliases: [],
    detectionSignals: ['roleplay', 'role play', 'act out', 'imagine you are', 'student a student b'],
    supportStatus: 'supported',
    runtimeMode: 'soft_speaking',
    validationMode: 'soft_ai_feedback',
    progressionMode: 'soft_completion',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: {
      ...SOFT_SPEAKING_BEHAVIOR,
      introRule: 'Set the scene. Assign roles clearly. Play as the other participant.',
    },
  },

  show_interest_agree_disagree: {
    canonicalType: 'show_interest_agree_disagree',
    aliases: [],
    detectionSignals: ['show interest', 'agree or disagree', 'do you agree', 'express interest', 'react to'],
    supportStatus: 'supported',
    runtimeMode: 'soft_speaking',
    validationMode: 'soft_ai_feedback',
    progressionMode: 'soft_completion',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: SOFT_SPEAKING_BEHAVIOR,
  },

  brainstorm_60_second: {
    canonicalType: 'brainstorm_60_second',
    aliases: [],
    detectionSignals: ['brainstorm', '60 seconds', 'how many can you', 'think of as many'],
    supportStatus: 'supported',
    runtimeMode: 'warmup_activation',
    validationMode: 'soft_ai_feedback',
    progressionMode: 'soft_completion',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: {
      ...SOFT_SPEAKING_BEHAVIOR,
      introRule: 'Give the topic. Encourage the student to produce as many words/ideas as possible quickly.',
    },
  },

  show_what_you_know: {
    canonicalType: 'show_what_you_know',
    aliases: [],
    detectionSignals: ['show what you know', 'what do you know', 'what can you remember'],
    supportStatus: 'supported',
    runtimeMode: 'warmup_activation',
    validationMode: 'soft_ai_feedback',
    progressionMode: 'soft_completion',
    voiceFriendliness: 'high',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: SOFT_SPEAKING_BEHAVIOR,
  },

  // ── SUPPORTED: Grammar explanation types ────────────────────────────────────

  grammar_focus: {
    canonicalType: 'grammar_focus',
    aliases: [],
    detectionSignals: ['grammar focus', 'grammar box', 'study the grammar', 'language focus'],
    supportStatus: 'supported',
    runtimeMode: 'grammar_explanation',
    validationMode: 'soft_ai_feedback',
    progressionMode: 'explanation_then_check',
    voiceFriendliness: 'medium',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: GRAMMAR_EXPLANATION_BEHAVIOR,
  },

  remember_this: {
    canonicalType: 'remember_this',
    aliases: [],
    detectionSignals: ['remember this', 'remember!', 'note this', 'important note'],
    supportStatus: 'supported',
    runtimeMode: 'teacher_explanation',
    validationMode: 'soft_ai_feedback',
    progressionMode: 'explanation_then_check',
    voiceFriendliness: 'medium',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: GRAMMAR_EXPLANATION_BEHAVIOR,
  },

  // ── POSTPONED: Listening ─────────────────────────────────────────────────────

  listening: {
    canonicalType: 'listening',
    aliases: ['listen', 'listening_task', 'audio_task'],
    detectionSignals: ['listen', 'track', 'audio', 'mp3', 'listen to the recording', 'listen and answer'],
    supportStatus: 'postponed',
    runtimeMode: 'future_listening_mode',
    validationMode: 'unsupported',
    progressionMode: 'skip',
    voiceFriendliness: 'not_applicable',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: true,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'skip',
    teacherBehavior: {
      ...UNSUPPORTED_BEHAVIOR,
      introRule: 'Explain that this exercise requires textbook audio. Offer to skip or do a related speaking task.',
    },
  },

  gap_fill_from_audio: {
    canonicalType: 'gap_fill_from_audio',
    aliases: [],
    detectionSignals: ['listen and fill', 'listen and complete', 'complete while listening'],
    supportStatus: 'postponed',
    runtimeMode: 'future_listening_mode',
    validationMode: 'unsupported',
    progressionMode: 'skip',
    voiceFriendliness: 'not_applicable',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: true,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'skip',
    teacherBehavior: UNSUPPORTED_BEHAVIOR,
  },

  listen_check_repeat: {
    canonicalType: 'listen_check_repeat',
    aliases: [],
    detectionSignals: ['listen check and repeat', 'listen and repeat', 'listen and check'],
    supportStatus: 'postponed',
    runtimeMode: 'future_listening_mode',
    validationMode: 'unsupported',
    progressionMode: 'skip',
    voiceFriendliness: 'not_applicable',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: true,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'speaking_prompt',
    teacherBehavior: {
      ...UNSUPPORTED_BEHAVIOR,
      introRule: 'This task requires textbook audio. Offer the student a speaking prompt instead.',
      downgradeStrategy: 'speaking_prompt',
    } as ExercisePolicy['teacherBehavior'],
  },

  pronunciation_focus: {
    canonicalType: 'pronunciation_focus',
    aliases: [],
    detectionSignals: ['pronunciation', 'stress the', 'word stress', 'sounds like'],
    supportStatus: 'postponed',
    runtimeMode: 'future_pronunciation_mode',
    validationMode: 'unsupported',
    progressionMode: 'skip',
    voiceFriendliness: 'not_applicable',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: true,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'skip',
    teacherBehavior: {
      ...UNSUPPORTED_BEHAVIOR,
      introRule: 'Pronunciation scoring API is not yet available. Explain and skip.',
    },
  },

  // ── POSTPONED: Reading ───────────────────────────────────────────────────────

  reading_long_text: {
    canonicalType: 'reading_long_text',
    aliases: ['reading', 'read_text', 'read_article'],
    detectionSignals: ['read the text', 'read the article', 'read the passage', 'reading text'],
    supportStatus: 'postponed',
    runtimeMode: 'future_reading_mode',
    validationMode: 'unsupported',
    progressionMode: 'future',
    voiceFriendliness: 'low',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: true,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'future_only',
    teacherBehavior: {
      ...UNSUPPORTED_BEHAVIOR,
      introRule: 'Long reading requires paragraph mode which is not yet available. Skip or summarize the topic verbally.',
    },
  },

  read_and_answer: {
    canonicalType: 'read_and_answer',
    aliases: ['read_article', 'answer_questions'],
    detectionSignals: ['read and answer', 'read the text and answer', 'answer the questions about the text'],
    supportStatus: 'supported',
    runtimeMode: 'reading_text',
    validationMode: 'soft_ai_feedback',
    progressionMode: 'locked_item',
    voiceFriendliness: 'medium',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: TEXT_READING_BEHAVIOR,
  },

  gapped_text: {
    canonicalType: 'gapped_text',
    aliases: ['gap_fill_text', 'choose_sentence'],
    detectionSignals: ['choose sentence a-f', 'sentences a-f', 'gaps 1-5', 'choose the sentence', 'fill the gaps with sentences'],
    supportStatus: 'supported',
    runtimeMode: 'reading_text',
    validationMode: 'matching_letter_or_text',
    progressionMode: 'locked_item',
    voiceFriendliness: 'medium',
    requiresOptions: true,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: {
      ...TEXT_READING_BEHAVIOR,
      introRule: 'Tell the student which gap to work on. Confirm that sentences A-F are visible on screen. Ask: which sentence fits gap N?',
      answerFormatRule: 'Student says a letter (A, B, C, D, E, or F). Accept letter only or letter + sentence.',
    },
  },

  find_in_text: {
    canonicalType: 'find_in_text',
    aliases: ['underline_in_text'],
    detectionSignals: ['find in the text', 'find words in the text', 'underline in the text'],
    supportStatus: 'supported',
    runtimeMode: 'reading_text',
    validationMode: 'deterministic_normalized',
    progressionMode: 'locked_item',
    voiceFriendliness: 'medium',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: {
      ...TEXT_READING_BEHAVIOR,
      introRule: 'Tell the student exactly what they are looking for in the text. Reference the visible item.',
      answerFormatRule: 'Student says the word or phrase they found in the text.',
    },
  },

  read_and_write_names: {
    canonicalType: 'read_and_write_names',
    aliases: ['who_said'],
    detectionSignals: ['read and write the names', 'write the names', 'who said', 'which person'],
    supportStatus: 'supported',
    runtimeMode: 'reading_text',
    validationMode: 'deterministic_normalized',
    progressionMode: 'locked_item',
    voiceFriendliness: 'medium',
    requiresOptions: false,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: {
      ...TEXT_READING_BEHAVIOR,
      introRule: 'Read the question aloud. Tell the student to find the name in their book.',
      answerFormatRule: 'Student says a person\'s name.',
    },
  },

  phrase_classification: {
    canonicalType: 'phrase_classification',
    aliases: ['categorize', 'sort_phrases', 'classify_phrases'],
    detectionSignals: ['decide whether', 'sort the phrases', 'classify the words', 'put in the correct group', 'parents say', 'teenagers say'],
    supportStatus: 'supported',
    runtimeMode: 'reading_text',
    validationMode: 'deterministic_normalized',
    progressionMode: 'locked_item',
    voiceFriendliness: 'medium',
    requiresOptions: true,
    requiresCorrectAnswer: true,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: true,
    downgradeStrategy: 'none',
    teacherBehavior: {
      ...TEXT_READING_BEHAVIOR,
      introRule: 'Confirm that the phrases are visible on screen. Tell the student the two categories. Ask one phrase at a time: which category does this phrase belong to?',
      answerFormatRule: 'Student says the category name (e.g. "Parents say" or "Teenagers say").',
    },
  },

  // ── POSTPONED: Writing ───────────────────────────────────────────────────────

  writing_task: {
    canonicalType: 'writing_task',
    aliases: ['writing', 'write'],
    detectionSignals: ['write an email', 'write a letter', 'write about', '100 words', 'write a paragraph', 'write a description'],
    supportStatus: 'postponed',
    runtimeMode: 'future_writing_mode',
    validationMode: 'unsupported',
    progressionMode: 'future',
    voiceFriendliness: 'low',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'teacher_explanation',
    teacherBehavior: {
      ...UNSUPPORTED_BEHAVIOR,
      introRule: 'Explain this as a homework or writing mode task. Do not force voice validation. Describe what a good answer includes.',
    },
  },

  writing_focus_analyse_model: {
    canonicalType: 'writing_focus_analyse_model',
    aliases: [],
    detectionSignals: ['analyse the model', 'writing focus', 'model answer', 'study the model text'],
    supportStatus: 'postponed',
    runtimeMode: 'future_writing_mode',
    validationMode: 'unsupported',
    progressionMode: 'future',
    voiceFriendliness: 'low',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: true,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'future_only',
    teacherBehavior: UNSUPPORTED_BEHAVIOR,
  },

  writing_order_paragraphs: {
    canonicalType: 'writing_order_paragraphs',
    aliases: [],
    detectionSignals: ['order the paragraphs', 'put the paragraphs in order', 'number the paragraphs'],
    supportStatus: 'postponed',
    runtimeMode: 'future_writing_mode',
    validationMode: 'unsupported',
    progressionMode: 'future',
    voiceFriendliness: 'low',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: true,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'future_only',
    teacherBehavior: UNSUPPORTED_BEHAVIOR,
  },

  writing_self_check: {
    canonicalType: 'writing_self_check',
    aliases: [],
    detectionSignals: ['self check', 'check your writing', 'review your answer', 'proofread'],
    supportStatus: 'postponed',
    runtimeMode: 'future_writing_mode',
    validationMode: 'unsupported',
    progressionMode: 'future',
    voiceFriendliness: 'low',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'future_only',
    teacherBehavior: UNSUPPORTED_BEHAVIOR,
  },

  // ── POSTPONED: Image / Table / Cartoon ──────────────────────────────────────

  complete_table: {
    canonicalType: 'complete_table',
    aliases: [],
    detectionSignals: ['complete the table', 'fill in the table', 'complete this chart'],
    supportStatus: 'postponed',
    runtimeMode: 'skipped',
    validationMode: 'unsupported',
    progressionMode: 'skip',
    voiceFriendliness: 'not_applicable',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: true,
    requiresLongText: false,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'skip',
    teacherBehavior: {
      ...UNSUPPORTED_BEHAVIOR,
      introRule: 'Table exercises require visual rendering. Skip or discuss the topic verbally.',
    },
  },

  complete_cartoon_captions: {
    canonicalType: 'complete_cartoon_captions',
    aliases: [],
    detectionSignals: ['cartoon', 'caption', 'speech bubble', 'complete the speech'],
    supportStatus: 'postponed',
    runtimeMode: 'skipped',
    validationMode: 'unsupported',
    progressionMode: 'skip',
    voiceFriendliness: 'not_applicable',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: true,
    requiresLongText: false,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'skip',
    teacherBehavior: UNSUPPORTED_BEHAVIOR,
  },

  exam_focus_unsupported: {
    canonicalType: 'exam_focus_unsupported',
    aliases: [],
    detectionSignals: ['exam focus', 'exam tip', 'exam strategy', 'use of english'],
    supportStatus: 'unsupported',
    runtimeMode: 'skipped',
    validationMode: 'unsupported',
    progressionMode: 'skip',
    voiceFriendliness: 'not_applicable',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'teacher_explanation',
    teacherBehavior: {
      ...UNSUPPORTED_BEHAVIOR,
      introRule: 'Exam focus sections are not structured exercises. Summarise the exam tip verbally.',
    },
  },

  // ── Fallback ─────────────────────────────────────────────────────────────────

  unknown: {
    canonicalType: 'unknown',
    aliases: [],
    detectionSignals: [],
    supportStatus: 'unsupported',
    runtimeMode: 'skipped',
    validationMode: 'unsupported',
    progressionMode: 'skip',
    voiceFriendliness: 'not_applicable',
    requiresOptions: false,
    requiresCorrectAnswer: false,
    requiresAudio: false,
    requiresImage: false,
    requiresLongText: false,
    allowInCurrentRuntime: false,
    downgradeStrategy: 'skip',
    teacherBehavior: {
      ...UNSUPPORTED_BEHAVIOR,
      introRule: 'Unknown exercise type. Skip and continue with supported exercises.',
    },
  },
}
